// Generated by CoffeeScript 1.4.0
var AssertionError, Realizer;

AssertionError = require('assert').AssertionError;

require('fing');

Realizer = (function() {

  function Realizer() {}

  Realizer.realizers = {};

  Realizer.createFunction = function(name, object, configuration, realization) {
    var key, originalFunction, realizer;
    key = object.fing.ref + ':' + name;
    if (object.fing.type === 'prototype') {
      originalFunction = object.prototype[name];
    } else {
      originalFunction = object[name];
    }
    if (typeof this.realizers[key] === 'undefined') {
      this.realizers[key] = {
        object: object,
        original: originalFunction,
        config: configuration,
        realizations: []
      };
      realizer = function() {
        var config, realizerCallback;
        object = Realizer.realizers[key].object;
        config = Realizer.realizers[key].config;
        realizerCallback = Realizer.realizers[key].realizations.shift();
        if (typeof realizerCallback === 'undefined') {
          throw new AssertionError({
            message: 'Unexpected call to ' + key
          });
        }
        realizerCallback({
          object: object,
          args: arguments
        });
        return config.returning;
      };
      if (object.fing.type === 'prototype') {
        object.prototype[name] = realizer;
      } else {
        object[name] = realizer;
      }
    }
    return this.realizers[key].realizations.push(realization);
  };

  return Realizer;

})();

module.exports = Realizer;
